Request stores location
CraftAcademy/reQuest_api pull request #23
Opened 2020-06-23 15:51 UTC by ViaMarcus

[PT Feature](https://www.pivotaltracker.com/story/show/173457186)
BRB doing README

2020-06-23 16:01 UTC, jysmys approved these changes
Looks skinny and slim for me!

2020-06-23 16:08 UTC, designerofthing approved these changes

2020-06-23 20:42 UTC, PaulineBA commented on spec/requests/api/my_request/requests/create_spec.rb
> +        expect(response_json['message']).to eq "Location can't be blank"
If visitor does not share location, the coords will be sent as coords { lat: undefined, long: undefined} from front end.
For future reference, if visitor not sharing location the Back end should serve the request list  distance:null to each one of them. So the distance will not be shown to that user. 
That's how we did it in the front end

2020-06-23 20:48 UTC, PaulineBA requested changes

2020-06-23 20:48 UTC, PaulineBA commented on spec/requests/api/my_request/requests/create_spec.rb
> +    describe 'no location is provided' do
If visitor does not share location, the coords will be sent as coords { lat: undefined, long: undefined} from front end.
For future reference, if visitor not sharing location the Back end should serve the request list distance:null to each one of them. So the distance will not be shown to that user.
That's how we did it in the front end

2020-06-24 15:50 UTC, kermit-klein approved these changes

2020-06-25 07:54 UTC, merged